
on:
  push:
  workflow_dispatch:

env:
  MONOLITH_VERSION: ${{ vars.MONOLITH_VERSION || '2.10.1' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install ruby dependencies
        run: bundle install

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Build code assets
        run: make presentation

      - name: Build presentation file
        run: |
          mkdir -p _site/resources
          cp -r resources/styles/ _site/resources/
          cp presentation.html _site/index.html

      - name: Install html single-file packager
        if: github.ref == 'refs/heads/master'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | RUSTUP_INIT_SKIP_PATH_CHECK=yes sh -s -- -y
          echo "$HOME/.cargo/bin" >"$GITHUB_PATH"
          "$HOME/.cargo/bin/cargo" install monolith --version ${{ env.MONOLITH_VERSION }}

      - name: Build presentation single-file
        if: github.ref == 'refs/heads/master'
        run: monolith _site/index.html -o _site/presentation-standalone.html

      - name: Build gh-pages archive
        uses: actions/upload-pages-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          path: _site/

  deploy:
    name: Release to GH-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
